### ISSUE TITLE
Doesn't work. Am I doing something wrong?

### ISSUE THREAD

**Issue by Hubro** [nakamuray/jedi-rpc.vim#2]
I have tried this plugin with Python 3.7.0 and 3.5.5. In both cases, activating this plugin makes vim-jedi stop working completely.

I have activated the plugin like this, using vim-plug:

```vim
Plug 'davidhalter/jedi-vim'
Plug 'nakamuray/jedi-rpc.vim'
```

Then I open vim from a terminal where I have virtualenv activated. I confirm this by running:

```
:!which python
:!python --version
:!pyenv version
:!pyenv which python
```

This produces respectively:

```
/home/tomas/.pyenv/shims/python
Python 3.5.5
test (set by PYENV_VERSION environment variable)
/home/tomas/.pyenv/versions/test/bin/python
```

I handle my virtualenvs using pyenv, but I have also tested activating the virtualenv manually in a fresh terminal like this:

```
source .pyenv/versions/test/bin/activate
```

And then launching vim, but the results are the same.

Now I open a Python file and type:

```python
import os
os.
```

As I type the final dot, I expect a list of completion suggestions. Instead, the footer says:

```
-- Omni completion (^O^N^P) Pattern not found
```

When I place the cursor on top of a variable and press `<Leader>g`. I expect the cursor to jump to the place where the variable was first assigned. Instead, I get an error:

```
Traceback (most recent call last):
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 213, in get_script
    environment=get_environment(),
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 127, in __call__
    return self._jedi_remote.remote_object_call(self._id, *args, **kwargs)
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 56, in remote_object_call
    return self._call_remote('remote_object_call', id, *args, **kwargs)
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 68, in _call_remote
    output = json.dumps({'func': func, 'args': args, 'kwargs': kwargs})
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Environment: 2.7.13 in /usr> is not JSON serializable
Traceback (most recent call last):
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 301, in goto
    definitions = script.goto_assignments()
AttributeError: 'NoneType' object has no attribute 'goto_assignments'
```

Trying `<Leader>d` appears to give the exact same error.

**Comment by Hubro** [comment]
Oh, and Shift+k produces this error:

```
Traceback (most recent call last):
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 213, in get_script
    environment=get_environment(),
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 127, in __call__
    return self._jedi_remote.remote_object_call(self._id, *args, **kwargs)
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 56, in remote_object_call
    return self._call_remote('remote_object_call', id, *args, **kwargs)
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 68, in _call_remote
    output = json.dumps({'func': func, 'args': args, 'kwargs': kwargs})
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Environment: 2.7.13 in /usr> is not JSON serializable
Traceback (most recent call last):
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 366, in show_documentation
    definitions = script.goto_definitions()
AttributeError: 'NoneType' object has no attribute 'goto_definitions'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/home/tomas/.vim/plug/jedi-vim/pythonx/jedi_vim.py", line 367, in show_documentation
    except jedi.NotFoundError:
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 65, in __getattr__
    return self._call_remote('get_from_jedi', name)
  File "/home/tomas/Dropbox/Personal/config_sync/vim/plug/jedi-rpc.vim/jedi_remote.py", line 88, in _call_remote
    import __builtin__
ImportError: No module named '__builtin__'
```

**Comment by nakamuray** [comment]
Because recent version of jedi has similar separate python process method to support venv, you don't need to use this workaround plugin anymore.

(I'll write this caution in README.)

**Comment by Hubro** [comment]
That's unfortunate. I couldn't get it to pick up my virtualenv all by itself either, and when browsing issues I basically get the impression that I shouldn't expect it to work.

I've switched to YouCompleteMe now, for most of the auto-completion functionality, but I wish I could simply get vim-jedi to work.
